services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: plantao_ja
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 10

  usuario-service:
    build: ./backend/plantao-ja-usuario-service
    container_name: usuario-service
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/plantao_ja?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - app-network

  hospital-service:
    build: ./backend/plantao-ja-hospital-service
    container_name: hospital-service
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/plantao_ja?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - app-network


plantao-service:
    build: 
      context: ./backend/plantao-ja-plantao-service 
      dockerfile: Dockerfile
    ports:
      - "8888:8083"
    environment:
      
      - HOSPITAL_API_URL=http://hospital-service:8080/hospital/
    networks:
      - app-network
    depends_on:
      - hospital-service 


  scraping-service:
    build: ./backend/plantao-ja-scraping-service
    container_name: scraping-service
    networks:
      - app-network
    
  gateway:
    build: ./backend/gateway
    container_name: gateway
    networks:
      - app-network

  frontend:
    build: ./frontend/plantao-ja/plantao-ja
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge